{
    "openapi": "3.1.0",
    "info": {
        "title": "TWIN - Test Endpoints",
        "description": "REST API for TWIN - Test Endpoints.",
        "version": "1.0.0",
        "license": {
            "name": "Apache 2.0 License",
            "url": "https://opensource.org/licenses/Apache-2.0"
        }
    },
    "servers": [
        {
            "url": "https://localhost"
        }
    ],
    "tags": [
        {
            "name": "Auditable Item Graph",
            "description": "Endpoints which are modelled to access an auditable item graph contract."
        }
    ],
    "paths": {
        "/auditable-item-graph": {
            "post": {
                "operationId": "auditableItemGraphCreate",
                "summary": "Create a new graph vertex",
                "tags": [
                    "Auditable Item Graph"
                ],
                "security": [
                    {
                        "jwtBearerAuthScheme": []
                    }
                ],
                "requestBody": {
                    "description": "Create an auditable item graph vertex.",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/AuditableItemGraphCreateRequest"
                            },
                            "examples": {
                                "auditableItemGraphCreateRequestExample": {
                                    "value": {
                                        "metadata": {
                                            "@context": "http://schema.org/",
                                            "@type": "Note",
                                            "content": "This is a simple note"
                                        },
                                        "aliases": [
                                            {
                                                "id": "bar456",
                                                "metadata": {
                                                    "@context": "http://schema.org/",
                                                    "@type": "Note",
                                                    "content": "This is a simple note"
                                                }
                                            },
                                            {
                                                "id": "foo321",
                                                "metadata": {
                                                    "@context": "http://schema.org/",
                                                    "@type": "Note",
                                                    "content": "This is a simple note"
                                                }
                                            }
                                        ],
                                        "resources": [
                                            {
                                                "id": "resource1",
                                                "metadata": {
                                                    "@context": "http://schema.org/",
                                                    "@type": "Note",
                                                    "content": "This is a simple note"
                                                }
                                            },
                                            {
                                                "id": "resource2",
                                                "metadata": {
                                                    "@context": "http://schema.org/",
                                                    "@type": "Note",
                                                    "content": "This is a simple note"
                                                }
                                            }
                                        ],
                                        "edges": [
                                            {
                                                "id": "edge1",
                                                "relationship": "frenemy",
                                                "metadata": {
                                                    "@context": "http://schema.org/",
                                                    "@type": "Note",
                                                    "content": "This is a simple note"
                                                }
                                            },
                                            {
                                                "id": "edge2",
                                                "relationship": "end",
                                                "metadata": {
                                                    "@context": "http://schema.org/",
                                                    "@type": "Note",
                                                    "content": "This is a simple note"
                                                }
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "The rest request ended in created response.",
                        "headers": {
                            "Location": {
                                "schema": {
                                    "type": "string"
                                },
                                "description": "e.g. aig:1234567890"
                            }
                        }
                    },
                    "400": {
                        "description": "The server cannot process the request, see the content for more details.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                },
                                "examples": {
                                    "exampleResponse": {
                                        "value": {
                                            "name": "GeneralError",
                                            "message": "component.error",
                                            "properties": {
                                                "foo": "bar"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "You are not authorized to use the API or no credentials were supplied, see the content for more details.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                },
                                "examples": {
                                    "exampleResponse": {
                                        "value": {
                                            "name": "UnauthorizedError",
                                            "message": "component.error"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "The server has encountered a situation it does not know how to handle, see the content for more details.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                },
                                "examples": {
                                    "exampleResponse": {
                                        "value": {
                                            "name": "InternalServerError",
                                            "message": "component.error"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "operationId": "auditableItemGraphList",
                "summary": "Query graph vertices by id or alias",
                "tags": [
                    "Auditable Item Graph"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "description": "The id or alias to try and find.",
                        "in": "query",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "idMode",
                        "description": "Which field to look in with the id, defaults to both.",
                        "in": "query",
                        "required": false,
                        "schema": {
                            "type": "string",
                            "enum": [
                                "id",
                                "alias",
                                "both"
                            ]
                        }
                    },
                    {
                        "name": "orderBy",
                        "description": "The order for the results, default to created.",
                        "in": "query",
                        "required": false,
                        "schema": {
                            "type": "string",
                            "enum": [
                                "created",
                                "updated"
                            ]
                        }
                    },
                    {
                        "name": "orderByDirection",
                        "description": "The direction for the order, defaults to desc.",
                        "in": "query",
                        "required": false,
                        "schema": {
                            "$ref": "#/components/schemas/SortDirection"
                        }
                    },
                    {
                        "name": "properties",
                        "description": "The properties to return as a comma separated list, defaults to \"id,created,aliases,metadata\".",
                        "in": "query",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "cursor",
                        "description": "The optional cursor to get next chunk.",
                        "in": "query",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "pageSize",
                        "description": "The maximum number of entities in a page.",
                        "in": "query",
                        "required": false,
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "style": "simple"
                    }
                ],
                "security": [
                    {
                        "jwtBearerAuthScheme": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The response to getting the a list of the vertices with matching ids or aliases.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/AuditableItemGraphListResponse"
                                },
                                "examples": {
                                    "auditableItemGraphListResponseExample": {
                                        "value": {
                                            "entities": [
                                                {
                                                    "id": "0101010101010101010101010101010101010101010101010101010101010101",
                                                    "aliases": [
                                                        {
                                                            "id": "foo4",
                                                            "created": 1234567890
                                                        }
                                                    ]
                                                }
                                            ],
                                            "cursor": "1"
                                        }
                                    }
                                }
                            },
                            "application/ld+json": {
                                "schema": {
                                    "$ref": "#/components/schemas/AuditableItemGraphListResponse"
                                },
                                "examples": {
                                    "auditableItemGraphJsonLdListResponseExample": {
                                        "value": {
                                            "@context": "https://schema.twindev.org/aig/",
                                            "@graph": [
                                                {
                                                    "@type": "vertex",
                                                    "id": "aig:1234567890",
                                                    "created": "2024-08-22T11:55:16.271Z",
                                                    "updated": "2024-08-22T11:55:16.271Z",
                                                    "metadata": {
                                                        "@context": "http://schema.org/",
                                                        "@type": "Note",
                                                        "content": "This is a simple note"
                                                    },
                                                    "aliases": [
                                                        {
                                                            "@type": "alias",
                                                            "created": "2024-08-22T11:55:16.271Z",
                                                            "id": "tst:1234567890"
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    }
                                }
                            }
                        },
                        "headers": {
                            "Content-Type": {
                                "schema": {
                                    "type": "string"
                                },
                                "description": "e.g. application/ld+json"
                            }
                        }
                    },
                    "400": {
                        "description": "The server cannot process the request, see the content for more details.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                },
                                "examples": {
                                    "exampleResponse": {
                                        "value": {
                                            "name": "GeneralError",
                                            "message": "component.error",
                                            "properties": {
                                                "foo": "bar"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "You are not authorized to use the API or no credentials were supplied, see the content for more details.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                },
                                "examples": {
                                    "exampleResponse": {
                                        "value": {
                                            "name": "UnauthorizedError",
                                            "message": "component.error"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "The server has encountered a situation it does not know how to handle, see the content for more details.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                },
                                "examples": {
                                    "exampleResponse": {
                                        "value": {
                                            "name": "InternalServerError",
                                            "message": "component.error"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auditable-item-graph/{id}": {
            "get": {
                "operationId": "auditableItemGraphGet",
                "summary": "Get a graph vertex",
                "tags": [
                    "Auditable Item Graph"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "description": "The id of the vertex to get.",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "style": "simple",
                        "example": "aig:1234567890"
                    },
                    {
                        "name": "includeDeleted",
                        "description": "Whether to include deleted aliases, resource, edges, defaults to false.",
                        "in": "query",
                        "required": false,
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    {
                        "name": "includeChangesets",
                        "description": "Whether to include the changesets of the vertex, defaults to false.",
                        "in": "query",
                        "required": false,
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    {
                        "name": "verifySignatureDepth",
                        "description": "How many signatures to verify, none, current or all, defaults to \"none\".",
                        "in": "query",
                        "required": false,
                        "schema": {
                            "$ref": "#/components/schemas/VerifyDepth"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "style": "simple",
                        "example": "application/json"
                    }
                ],
                "security": [
                    {
                        "jwtBearerAuthScheme": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response to getting an auditable item graph vertex.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/AuditableItemGraphGetResponse"
                                },
                                "examples": {
                                    "auditableItemGraphGetResponseExample": {
                                        "value": {
                                            "id": "aig:1234567890",
                                            "created": 1234567890,
                                            "updated": 1234567890,
                                            "metadata": {
                                                "@context": "http://schema.org/",
                                                "@type": "Note",
                                                "content": "This is a simple note"
                                            },
                                            "aliases": [
                                                {
                                                    "id": "tst:1234567890",
                                                    "created": 1234567890
                                                }
                                            ]
                                        }
                                    }
                                }
                            },
                            "application/ld+json": {
                                "schema": {
                                    "$ref": "#/components/schemas/AuditableItemGraphGetResponse"
                                },
                                "examples": {
                                    "auditableItemGraphJsonLdGetResponseExample": {
                                        "value": {
                                            "@context": "https://schema.twindev.org/aig/",
                                            "@type": "vertex",
                                            "id": "aig:1234567890",
                                            "created": "2024-08-22T11:55:16.271Z",
                                            "updated": "2024-08-22T11:55:16.271Z",
                                            "metadata": {
                                                "@context": "http://schema.org/",
                                                "@type": "Note",
                                                "content": "This is a simple note"
                                            },
                                            "aliases": [
                                                {
                                                    "@type": "alias",
                                                    "created": "2024-08-22T11:55:16.271Z",
                                                    "id": "tst:1234567890"
                                                }
                                            ]
                                        }
                                    }
                                }
                            }
                        },
                        "headers": {
                            "Content-Type": {
                                "schema": {
                                    "type": "string"
                                },
                                "description": "e.g. application/ld+json"
                            }
                        }
                    },
                    "400": {
                        "description": "The server cannot process the request, see the content for more details.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                },
                                "examples": {
                                    "exampleResponse": {
                                        "value": {
                                            "name": "GeneralError",
                                            "message": "component.error",
                                            "properties": {
                                                "foo": "bar"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "You are not authorized to use the API or no credentials were supplied, see the content for more details.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                },
                                "examples": {
                                    "exampleResponse": {
                                        "value": {
                                            "name": "UnauthorizedError",
                                            "message": "component.error"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "The server has encountered a situation it does not know how to handle, see the content for more details.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                },
                                "examples": {
                                    "exampleResponse": {
                                        "value": {
                                            "name": "InternalServerError",
                                            "message": "component.error"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "operationId": "auditableItemGraphUpdate",
                "summary": "Update a graph vertex",
                "tags": [
                    "Auditable Item Graph"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "description": "The id of the vertex to update.",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "style": "simple",
                        "example": "aig:1234567890"
                    }
                ],
                "security": [
                    {
                        "jwtBearerAuthScheme": []
                    }
                ],
                "requestBody": {
                    "description": "Update an auditable item graph vertex.",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/AuditableItemGraphUpdateRequest"
                            },
                            "examples": {
                                "auditableItemGraphUpdateRequestExample": {
                                    "value": {
                                        "metadata": {
                                            "@context": "http://schema.org/",
                                            "@type": "Note",
                                            "content": "This is a simple note"
                                        },
                                        "aliases": [
                                            {
                                                "id": "bar456",
                                                "metadata": {
                                                    "@context": "http://schema.org/",
                                                    "@type": "Note",
                                                    "content": "This is a simple note"
                                                }
                                            },
                                            {
                                                "id": "foo321",
                                                "metadata": {
                                                    "@context": "http://schema.org/",
                                                    "@type": "Note",
                                                    "content": "This is a simple note"
                                                }
                                            }
                                        ],
                                        "resources": [
                                            {
                                                "id": "resource1",
                                                "metadata": {
                                                    "@context": "http://schema.org/",
                                                    "@type": "Note",
                                                    "content": "This is a simple note"
                                                }
                                            },
                                            {
                                                "id": "resource2",
                                                "metadata": {
                                                    "@context": "http://schema.org/",
                                                    "@type": "Note",
                                                    "content": "This is a simple note"
                                                }
                                            }
                                        ],
                                        "edges": [
                                            {
                                                "id": "edge1",
                                                "relationship": "frenemy",
                                                "metadata": {
                                                    "@context": "http://schema.org/",
                                                    "@type": "Note",
                                                    "content": "This is a simple note"
                                                }
                                            },
                                            {
                                                "id": "edge2",
                                                "relationship": "end",
                                                "metadata": {
                                                    "@context": "http://schema.org/",
                                                    "@type": "Note",
                                                    "content": "This is a simple note"
                                                }
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "204": {
                        "description": "The rest request ended in success with no data."
                    },
                    "400": {
                        "description": "The server cannot process the request, see the content for more details.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                },
                                "examples": {
                                    "exampleResponse": {
                                        "value": {
                                            "name": "GeneralError",
                                            "message": "component.error",
                                            "properties": {
                                                "foo": "bar"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "You are not authorized to use the API or no credentials were supplied, see the content for more details.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                },
                                "examples": {
                                    "exampleResponse": {
                                        "value": {
                                            "name": "UnauthorizedError",
                                            "message": "component.error"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "The server has encountered a situation it does not know how to handle, see the content for more details.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                },
                                "examples": {
                                    "exampleResponse": {
                                        "value": {
                                            "name": "InternalServerError",
                                            "message": "component.error"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "AuditableItemGraphCreateRequest": {
                "type": "object",
                "properties": {
                    "metadata": {
                        "$ref": "https://schema.twindev.org/json-ld/JsonLdNodeObject"
                    },
                    "aliases": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string"
                                },
                                "format": {
                                    "type": "string"
                                },
                                "metadata": {
                                    "$ref": "https://schema.twindev.org/json-ld/JsonLdNodeObject"
                                }
                            },
                            "required": [
                                "id"
                            ],
                            "additionalProperties": false
                        },
                        "description": "Alternative aliases that can be used to identify the vertex."
                    },
                    "resources": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string"
                                },
                                "metadata": {
                                    "$ref": "https://schema.twindev.org/json-ld/JsonLdNodeObject"
                                }
                            },
                            "required": [
                                "id"
                            ],
                            "additionalProperties": false
                        },
                        "description": "The resources attached to the vertex."
                    },
                    "edges": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string"
                                },
                                "relationship": {
                                    "type": "string"
                                },
                                "metadata": {
                                    "$ref": "https://schema.twindev.org/json-ld/JsonLdNodeObject"
                                }
                            },
                            "required": [
                                "id",
                                "relationship"
                            ],
                            "additionalProperties": false
                        },
                        "description": "The edges connected to the vertex."
                    }
                },
                "additionalProperties": false,
                "description": "The data to be used in the vertex."
            },
            "AuditableItemGraphGetResponse": {
                "anyOf": [
                    {
                        "$ref": "https://schema.twindev.org/json-ld/JsonLdDocument"
                    },
                    {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "verified": {
                                "type": "boolean",
                                "description": "Whether the vertex and its elements have been verified."
                            },
                            "changesetsVerification": {
                                "type": "array",
                                "items": {
                                    "$ref": "https://schema.twindev.org/aig/AuditableItemGraphVerification"
                                },
                                "description": "The verification for the changesets including any failure information."
                            },
                            "metadata": {
                                "$ref": "https://schema.twindev.org/json-ld/JsonLdNodeObject",
                                "description": "The metadata to associate with the element as JSON-LD."
                            },
                            "id": {
                                "type": "string",
                                "description": "The id of the element."
                            },
                            "created": {
                                "type": "number",
                                "description": "The timestamp of when the element was created."
                            },
                            "updated": {
                                "type": "number",
                                "description": "The timestamp of when the element was updated."
                            },
                            "nodeIdentity": {
                                "type": "string",
                                "description": "The identity of the node which controls the vertex."
                            },
                            "aliases": {
                                "type": "array",
                                "items": {
                                    "$ref": "https://schema.twindev.org/aig/AuditableItemGraphAlias"
                                },
                                "description": "Alternative aliases that can be used to identify the vertex."
                            },
                            "resources": {
                                "type": "array",
                                "items": {
                                    "$ref": "https://schema.twindev.org/aig/AuditableItemGraphResource"
                                },
                                "description": "The resources attached to the vertex."
                            },
                            "edges": {
                                "type": "array",
                                "items": {
                                    "$ref": "https://schema.twindev.org/aig/AuditableItemGraphEdge"
                                },
                                "description": "Edges connected to the vertex."
                            },
                            "changesets": {
                                "type": "array",
                                "items": {
                                    "$ref": "https://schema.twindev.org/aig/AuditableItemGraphChangeset"
                                },
                                "description": "Changesets for the vertex."
                            }
                        },
                        "required": [
                            "created",
                            "id"
                        ]
                    }
                ],
                "description": "The response body, if accept header is set to application/ld+json the return object is JSON-LD document."
            },
            "AuditableItemGraphListResponse": {
                "anyOf": [
                    {
                        "$ref": "https://schema.twindev.org/json-ld/JsonLdDocument"
                    },
                    {
                        "type": "object",
                        "properties": {
                            "entities": {
                                "type": "array",
                                "items": {
                                    "$ref": "https://schema.twindev.org/aig/AuditableItemGraphVertex"
                                },
                                "description": "The entities, which can be partial if a limited keys list was provided."
                            },
                            "cursor": {
                                "type": "string",
                                "description": "An optional cursor, when defined can be used to call find to get more entities."
                            }
                        },
                        "additionalProperties": false
                    }
                ],
                "description": "The response payload."
            },
            "AuditableItemGraphUpdateRequest": {
                "type": "object",
                "properties": {
                    "metadata": {
                        "$ref": "https://schema.twindev.org/json-ld/JsonLdNodeObject"
                    },
                    "aliases": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string"
                                },
                                "format": {
                                    "type": "string"
                                },
                                "metadata": {
                                    "$ref": "https://schema.twindev.org/json-ld/JsonLdNodeObject"
                                }
                            },
                            "required": [
                                "id"
                            ],
                            "additionalProperties": false
                        },
                        "description": "Alternative aliases that can be used to identify the vertex."
                    },
                    "resources": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string"
                                },
                                "metadata": {
                                    "$ref": "https://schema.twindev.org/json-ld/JsonLdNodeObject"
                                }
                            },
                            "required": [
                                "id"
                            ],
                            "additionalProperties": false
                        },
                        "description": "The resources attached to the vertex."
                    },
                    "edges": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string"
                                },
                                "relationship": {
                                    "type": "string"
                                },
                                "metadata": {
                                    "$ref": "https://schema.twindev.org/json-ld/JsonLdNodeObject"
                                }
                            },
                            "required": [
                                "id",
                                "relationship"
                            ],
                            "additionalProperties": false
                        },
                        "description": "The edges connected to the vertex."
                    }
                },
                "additionalProperties": false,
                "description": "The data to be used in the vertex."
            },
            "Error": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The name for the error."
                    },
                    "message": {
                        "type": "string",
                        "description": "The message for the error."
                    },
                    "source": {
                        "type": "string",
                        "description": "The source of the error."
                    },
                    "properties": {
                        "type": "object",
                        "additionalProperties": {},
                        "description": "Any additional information for the error."
                    },
                    "stack": {
                        "type": "string",
                        "description": "The stack trace for the error."
                    },
                    "inner": {
                        "$ref": "#/components/schemas/Error"
                    }
                },
                "required": [
                    "name",
                    "message"
                ],
                "additionalProperties": false,
                "description": "Model to describe serialized error."
            },
            "SortDirection": {
                "anyOf": [
                    {
                        "type": "string",
                        "const": "asc",
                        "description": "Ascending."
                    },
                    {
                        "type": "string",
                        "const": "desc",
                        "description": "Descending."
                    }
                ],
                "description": "The sort directions."
            },
            "VerifyDepth": {
                "anyOf": [
                    {
                        "type": "string",
                        "const": "none",
                        "description": "Do not verify any signatures."
                    },
                    {
                        "type": "string",
                        "const": "current",
                        "description": "Verify only the most recent signature."
                    },
                    {
                        "type": "string",
                        "const": "all",
                        "description": "Verify all the signatures."
                    }
                ],
                "description": "How deep to verify the signatures."
            }
        },
        "securitySchemes": {
            "jwtBearerAuthScheme": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}